#!/usr/bin/env perl

use 5.18.0;
use strict;

use Data::Dumper  qw( Dumper );

open my $a, 'versions';

chomp(my @a=<$a>);
my %a=map split(/\t+/,$_,2),@a;

my $infh;
if ( @ARGV ) {
  open $infh, '<', $ARGV[0]
    or die "failed to open '$ARGV[0]' for reading: $!\n";
} else {
  $infh  = *STDIN{IO};
}

my $result = '';
while ( <$infh> ) {
  s/\b([\w-]+?)((-\d+)*)(?=[ ,]|$)/exists $a{$1} ? "$1-$a{$1}" : "$1$2"/eg;
  $result .= $_;
}

if ( @ARGV ) {
  my $outfn = $ARGV[0];
  my $bakfn = "$outfn.bak";
  if ( -e $outfn ) {
    rename $outfn, $bakfn
      or die "rename $outfn -> $bakfn failed: $!\n";
  }
  open my $outfh, '>', $outfn
    or die "failed to open '$outfn' for writing: $!\n";
  print $outfh $result;
  close $outfh
    or die "failed to close '$outfn' after writing: $!\n";
} else {
  print $result;
}
